import type { Metadata } from "next";
import { Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";

import Sidebar from '../components/Sidebar';
import Header from '../components/Header';

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pacifico",
});

const geistSans = Geist_Mono({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ready Site",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${pacifico.variable} flex min-h-screen`}
      >
        <Sidebar />
        <div className="flex-1 bg-amber-50">
          <Header />
          <main className="p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}

